# Financial services

## This project is designed to study the organisation type of finance company

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

## This data set is sourced by kaggle
Financil services dataset :-https://www.kaggle.com/datasets/anuragbantu/finance-companies-in-india

In [2]:
financial_services=pd.read_csv("Financial_Services.csv")

# Taking a brief overview of our data

In [3]:
financial_services.head()

Unnamed: 0              name  rating          reviews company_type  \
0           0        ICICI Bank     4.0  (33.6k Reviews)       Public   
1           1         HDFC Bank     4.0  (37.9k Reviews)       Public   
2           2  HCL Technologies     3.9  (17.4k Reviews)       Public   
3           3         Axis Bank     3.9  (18.3k Reviews)       Public   
4           4               IBM     4.2  (20.7k Reviews)       Public   

                    Head_Quarters    Company_Age             No_of_Employee  
0  Mumbai,Maharashtra + 1020 more   28 years old  1 Lakh+ Employees (India)  
1  Mumbai,Maharashtra + 1168 more   28 years old  1 Lakh+ Employees (India)  
2  Noida,Uttar Pradesh + 138 more   31 years old  1 Lakh+ Employees (India)  
3  Mumbai,Maharashtra + 1041 more   29 years old  1 Lakh+ Employees (India)  
4      Armonk,New York + 115 more  111 years old  1 Lakh+ Employees (India)

## Here we remove Unnamed: 0 column as it does not any meaningful information except index, which is not required in any case

In [4]:
financial_services=financial_services.drop("Unnamed: 0",axis=1);

In [5]:
financial_services.dtypes

name               object
rating            float64
reviews            object
company_type       object
Head_Quarters      object
Company_Age        object
No_of_Employee     object
dtype: object

In [6]:
financial_services.shape

(8970, 7)

In [7]:
financial_services.isna().sum()

name                 0
rating              20
reviews              0
company_type       938
Head_Quarters     2926
Company_Age       4878
No_of_Employee    6638
dtype: int64

# Making a missing columns to get the future references

In [8]:
for label, content in financial_services.items():
    if pd.isnull(content).sum():
        financial_services[label+"_is_missing"] = pd.isnull(content)

# Now we get the information about the number of missing values

In [9]:
financial_services.isna().sum()

name                            0
rating                         20
reviews                         0
company_type                  938
Head_Quarters                2926
Company_Age                  4878
No_of_Employee               6638
rating_is_missing               0
company_type_is_missing         0
Head_Quarters_is_missing        0
Company_Age_is_missing          0
No_of_Employee_is_missing       0
dtype: int64

### Here we can see only 20/8970 are missing in rating column so we can ignore the missing possiblity of it

In [10]:
financial_services.drop("rating_is_missing",axis=1);

## Here we are study about the irregularity of data by checking their unique values

In [11]:
pd.unique(financial_services["name"])

array(['ICICI Bank', 'HDFC Bank', 'HCL Technologies', ..., 'W4Consult',
       'Shastra Micro Sy...', 'Catallyst Conste...'], dtype=object)

In [12]:
pd.unique(financial_services["rating"])

array([4. , 3.9, 4.2, 3.8, 4.1, 4.3, 4.4, 3.7, 3.6, 3. , 3.4, 3.5, 3.1,
       2.8, 4.5, 3.2, 3.3, 4.6, 4.9, 2.9, 4.8, 4.7, 2.5, 2.7, 2.1, 2.3,
       1.8, 2.6, 5. , 1.6, 1.7, 2.4, 2. , 1.5, 2.2, 1.9, 1. , 1.1, 1.2,
       1.3, 1.4, nan])

In [13]:
pd.unique(financial_services["reviews"])[0:50]

array(['(33.6k Reviews)', '(37.9k Reviews)', '(17.4k Reviews)',
       '(18.3k Reviews)', '(20.7k Reviews)', '(12.9k Reviews)',
       '(13.2k Reviews)', '(6.6k Reviews)', '(5.7k Reviews)',
       '(4.9k Reviews)', '(4.5k Reviews)', '(4.4k Reviews)',
       '(4.2k Reviews)', '(5.4k Reviews)', '(3.7k Reviews)',
       '(3.5k Reviews)', '(3.4k Reviews)', '(3.3k Reviews)',
       '(3.1k Reviews)', '(2.5k Reviews)', '(2.4k Reviews)',
       '(2.3k Reviews)', '(4.7k Reviews)', '(2.2k Reviews)',
       '(2k Reviews)', '(2.1k Reviews)', '(1.9k Reviews)',
       '(5.5k Reviews)', '(1.7k Reviews)', '(2.9k Reviews)',
       '(1.6k Reviews)', '(1.5k Reviews)', '(1.4k Reviews)',
       '(15.3k Reviews)', '(1.3k Reviews)', '(1.2k Reviews)',
       '(3.9k Reviews)', '(1.1k Reviews)', '(2.7k Reviews)',
       '(1k Reviews)', '(996 Reviews)', '(994 Reviews)', '(978 Reviews)',
       '(959 Reviews)', '(958 Reviews)', '(954 Reviews)', '(938 Reviews)',
       '(925 Reviews)', '(924 Reviews)', '(915 Revie

In [14]:
pd.unique(financial_services["company_type"])[0:50]

array(['Public', 'Private', 'JV', 'Government',
       'Mumbai,Maharashtra + 334 more', 'Mumbai + 218 more',
       'Mumbai,Maharashtra + 188 more', 'Mumbai + 102 more',
       'Bangalore + 211 more', 'Gurgaon/Gurugram,Haryana + 105 more',
       'Mumbai,Maharashtra + 110 more', 'New York City,New York + 2 more',
       'Munich + 6 more', 'Mumbai,Maharashtra + 93 more',
       'Hyderabad + 16 more', 'Gurgaon/Gurugram + 64 more',
       'Mumbai + 52 more', 'Mumbai + 62 more', 'New Delhi + 84 more',
       'London + 6 more', 'Jalandhar + 37 more', 'Melbourne + 2 more',
       'Salem + 8 more', 'Mumbai,Maharashtra + 25 more',
       'Mumbai,Maharashtra + 60 more', 'LLP', 'New Delhi + 52 more',
       'Mumbai,Maharashtra + 35 more', 'Hamilton + 8 more',
       'Stockholm + 2 more', 'Manchester,Greater Manchester + 72 more',
       'Mumbai + 49 more', 'Atlanta + 10 more',
       'Jalandhar,Punjab + 43 more', 'Noida + 15 more', 'Pune + 53 more',
       'Navi Mumbai + 53 more', 'Mumbai + 47 m

In [15]:
pd.unique(financial_services["Head_Quarters"])

array(['Mumbai,Maharashtra + 1020 more', 'Mumbai,Maharashtra + 1168 more',
       'Noida,Uttar Pradesh + 138 more', ..., 'Rajkot,Gujrat',
       '71 years old', 'San Jose,California'], dtype=object)

In [16]:
pd.unique(financial_services["Company_Age"])[0:50]

array(['28 years old', '31 years old', '29 years old', '111 years old',
       '15 years old', '19 years old', '20 years old', '4 years old',
       '18 years old', '22 years old', '6 years old', '35 years old',
       '21 years old', '5 years old', '27 years old', '74 years old',
       '170 years old', '73 years old', '24 years old', '11 years old',
       '1 Lakh+ Employees (India)', '135 years old', '44 years old',
       '10k-50k Employees (India)', '172 years old', '152 years old',
       '1k-5k Employees (India)', '92 years old', '53 years old',
       '13 years old', '66 years old', '26 years old',
       '50k-1 Lakh Employees (India)', '38 years old', '36 years old',
       '47 years old', '230 years old', '16 years old', '65 years old',
       '332 years old', '58 years old', '14 years old', '9 years old',
       '17 years old', '105 years old', '210 years old', nan,
       '114 years old', '10 years old', '34 years old'], dtype=object)

In [17]:
pd.unique(financial_services["No_of_Employee"])

array(['1 Lakh+ Employees (India)', '50k-1 Lakh Employees (India)',
       '10k-50k Employees (India)', '1k-5k Employees (India)', nan,
       '5k-10k Employees (India)', '501-1k Employees (India)',
       '201-500 Employees (India)', '51-200 Employees (India)',
       '11-50 Employees (India)', '201-500 Employees (Global)',
       '1-10 Employees (India)', '1k-5k Employees (Global)',
       '5k-10k Employees (Global)', '501-1k Employees (Global)',
       '10k-50k Employees (Global)', '51-200 Employees (Global)',
       '11-50 Employees (Global)', '1 Lakh+ Employees (Global)',
       '50k-1 Lakh Employees (Global)', '10k+ Employees (Global)',
       '2-10 Employees (Global)', '1-10 Employees (Global)'], dtype=object)

# Defining some function to clean data

### By reviewing the data we can make a conclusion that value of some attributes is shifted to left side of it columns , so here we make different function to correct the value of columns.

In [18]:
def correct_the_column_company_type(df,column1,column2):
    for i in range(0,len(df)):
        if (not(df[column1+"_is_missing"][i]) and (df[column2+"_is_missing"][i])):
            if (df[column1][i] not in ['Public', 'Private', 'JV', 'Government','LLP',
                                       'Partnership','NGO/NPO', 'LLC', 'Proprietorship']):
                df[column2][i]=df[column1][i]
                df[column2+"_is_missing"][i]=False
                df[column1][i]=np.nan
                df[column1+"_is_missing"][i]=True

In [19]:
def correct_the_column_employee(df,column1,column2):
    for i in range(0,len(df)):
        if (not(df[column1+"_is_missing"][i]) and (df[column2+"_is_missing"][i])):
            if ('Employee' in df[column1][i]):
                df[column2][i]=df[column1][i]
                df[column2+"_is_missing"][i]=False
                df[column1][i]=np.nan
                df[column1+"_is_missing"][i]=True

In [20]:
def correct_the_column_year(df,column1,column2):
    for i in range(0,len(df)):
        if (not(df[column1+"_is_missing"][i]) and (df[column2+"_is_missing"][i])):
            if ('old' in df[column1][i]):
                df[column2][i]=df[column1][i]
                df[column2+"_is_missing"][i]=False
                df[column1][i]=np.nan
                df[column1+"_is_missing"][i]=True

In [21]:
def number_of_hq(df,column1,column2):
    financial_services[column2] = financial_services[column1]
    financial_services[column2] = financial_services[column2].astype(
        'str').str.extractall('(\d+)').unstack().fillna('').sum(axis=1).astype(int)
    for i in range(0,len(df)):
        if (df[column1+"_is_missing"][i]==True):
            continue
        elif ("+" in df[column1][i]):
            df[column2][i]=(df[column2][i])+1
        else:
            df[column2][i]=1
        
    return None

In [22]:
def correct_the_column_reviews(df,column1,column2):
    for i in range(0,len(df)):
        if ('k'in df[column1][i] and '.' in df[column1][i]):
            df[column2][i]=int(df[column1][i].replace("k Reviews)",'').replace("(",'').replace(".",''))*100
        elif ('k'in df[column1][i]):
            df[column2][i]=int(df[column1][i].replace("k Reviews)",'').replace("(",''))*1000
        else:
            df[column2][i]=int(df[column1][i].replace(" Reviews)",'').replace("(",''))
        
    return None

In [23]:
def making_global_column(df,column1,column2):
    for i in range(0,len(df)):
        if (df[column1+"_is_missing"][i]==True):
            df[column2][i]=np.nan
            continue
        elif ("Global" in df[column1][i]):
            df[column1][i]=(df[column1][i].replace(" Employees (Global)",''))
            df[column2][i]=True
        elif ("India" in df[column1][i]):
            df[column1][i]=(df[column1][i].replace(" Employees (India)",''))
            df[column2][i]=False
        
    return None

# Here we make a new column reviews in no by reviews column

In [24]:
financial_services["reviews_in_no"]=np.nan
correct_the_column_reviews(financial_services,"reviews","reviews_in_no")

# Here we calling these function to correct the data

In [25]:
correct_the_column_employee(financial_services,"company_type","No_of_Employee")
correct_the_column_employee(financial_services,"Head_Quarters","No_of_Employee")
correct_the_column_employee(financial_services,"Company_Age","No_of_Employee")

In [26]:
correct_the_column_year(financial_services,"Head_Quarters","Company_Age")
correct_the_column_year(financial_services,"company_type","Company_Age")

In [27]:
correct_the_column_company_type(financial_services,"company_type","Head_Quarters")

# Here we make a new column no. of headquarters from headquarters

In [28]:
financial_services["number_of_headquarters"]=np.nan
number_of_hq(financial_services,"Head_Quarters","number_of_headquarters")

# Here we make a new column company age in no of years from company age

In [29]:
financial_services["company_age_in_years"]=financial_services["Company_Age"].astype(
    'str').str.extractall('(\d+)').unstack().fillna('').sum(axis=1).astype(int)

# Here we make a new column Global to find about company's Global presence using No of Employee column

In [30]:
financial_services["Global"]=np.nan
financial_services["Global"].astype(bool)
making_global_column(financial_services,"No_of_Employee","Global")

# Now we are going to analyse the result of all the above manipulation we have done so far

In [31]:
pd.unique(financial_services["name"])

array(['ICICI Bank', 'HDFC Bank', 'HCL Technologies', ..., 'W4Consult',
       'Shastra Micro Sy...', 'Catallyst Conste...'], dtype=object)

In [32]:
pd.unique(financial_services["rating"])

array([4. , 3.9, 4.2, 3.8, 4.1, 4.3, 4.4, 3.7, 3.6, 3. , 3.4, 3.5, 3.1,
       2.8, 4.5, 3.2, 3.3, 4.6, 4.9, 2.9, 4.8, 4.7, 2.5, 2.7, 2.1, 2.3,
       1.8, 2.6, 5. , 1.6, 1.7, 2.4, 2. , 1.5, 2.2, 1.9, 1. , 1.1, 1.2,
       1.3, 1.4, nan])

In [33]:
pd.unique(financial_services["reviews"])[0:50]

array(['(33.6k Reviews)', '(37.9k Reviews)', '(17.4k Reviews)',
       '(18.3k Reviews)', '(20.7k Reviews)', '(12.9k Reviews)',
       '(13.2k Reviews)', '(6.6k Reviews)', '(5.7k Reviews)',
       '(4.9k Reviews)', '(4.5k Reviews)', '(4.4k Reviews)',
       '(4.2k Reviews)', '(5.4k Reviews)', '(3.7k Reviews)',
       '(3.5k Reviews)', '(3.4k Reviews)', '(3.3k Reviews)',
       '(3.1k Reviews)', '(2.5k Reviews)', '(2.4k Reviews)',
       '(2.3k Reviews)', '(4.7k Reviews)', '(2.2k Reviews)',
       '(2k Reviews)', '(2.1k Reviews)', '(1.9k Reviews)',
       '(5.5k Reviews)', '(1.7k Reviews)', '(2.9k Reviews)',
       '(1.6k Reviews)', '(1.5k Reviews)', '(1.4k Reviews)',
       '(15.3k Reviews)', '(1.3k Reviews)', '(1.2k Reviews)',
       '(3.9k Reviews)', '(1.1k Reviews)', '(2.7k Reviews)',
       '(1k Reviews)', '(996 Reviews)', '(994 Reviews)', '(978 Reviews)',
       '(959 Reviews)', '(958 Reviews)', '(954 Reviews)', '(938 Reviews)',
       '(925 Reviews)', '(924 Reviews)', '(915 Revie

In [34]:
pd.unique(financial_services["company_type"])[0:50]

array(['Public', 'Private', 'JV', 'Government', nan, 'LLP', 'Partnership',
       'NGO/NPO', 'LLC', 'Proprietorship'], dtype=object)

In [35]:
pd.unique(financial_services["Head_Quarters"])

array(['Mumbai,Maharashtra + 1020 more', 'Mumbai,Maharashtra + 1168 more',
       'Noida,Uttar Pradesh + 138 more', ..., 'Karol Bagh',
       'San Jose,California', 'Stockholm'], dtype=object)

In [36]:
pd.unique(financial_services["Company_Age"])[0:50]

array(['28 years old', '31 years old', '29 years old', '111 years old',
       '15 years old', '19 years old', '20 years old', '4 years old',
       '18 years old', '22 years old', '6 years old', '35 years old',
       '21 years old', '5 years old', '27 years old', '74 years old',
       '170 years old', '73 years old', '24 years old', '11 years old',
       '216 years old', '135 years old', '44 years old', nan,
       '172 years old', '152 years old', '92 years old', '53 years old',
       '13 years old', '66 years old', '26 years old', '165 years old',
       '38 years old', '36 years old', '47 years old', '230 years old',
       '16 years old', '65 years old', '332 years old', '58 years old',
       '14 years old', '9 years old', '17 years old', '105 years old',
       '210 years old', '114 years old', '10 years old', '34 years old',
       '7 years old', '25 years old'], dtype=object)

In [37]:
pd.unique(financial_services["No_of_Employee"])

array(['1 Lakh+', '50k-1 Lakh', '10k-50k', '1k-5k', '5k-10k', '501-1k',
       '201-500', '51-200', '11-50', '1-10', '10k+', nan, '2-10'],
      dtype=object)

In [38]:
pd.unique(financial_services["reviews_in_no"])[:50]

array([33600., 37900., 17400., 18300., 20700., 12900., 13200.,  6600.,
        5700.,  4900.,  4500.,  4400.,  4200.,  5400.,  3700.,  3500.,
        3400.,  3300.,  3100.,  2500.,  2400.,  2300.,  4700.,  2200.,
        2000.,  2100.,  1900.,  5500.,  1700.,  2900.,  1600.,  1500.,
        1400., 15300.,  1300.,  1200.,  3900.,  1100.,  2700.,  1000.,
         996.,   994.,   978.,   959.,   958.,   954.,   938.,   925.,
         924.,   915.])

In [39]:
pd.unique(financial_services["number_of_headquarters"])[:50]

array([1021., 1169.,  139., 1042.,  116.,  749.,  465.,  541.,   54.,
        370.,  354.,  394.,  294.,  396.,  592.,  421.,  375.,  463.,
         21.,  184.,  547.,   11.,  514.,  282.,  382.,  234.,  264.,
        287.,  335.,  195.,  419.,  378.,  408.,  472.,   18.,   34.,
         29.,  219.,  241.,  381.,   57.,   13.,   26.,  238.,  196.,
        165.,  175.,  206.,  180.,  349.])

In [40]:
pd.unique(financial_services["company_age_in_years"])

array([ 28.,  31.,  29., 111.,  15.,  19.,  20.,   4.,  18.,  22.,   6.,
        35.,  21.,   5.,  27.,  74., 170.,  73.,  24.,  11., 216., 135.,
        44.,  nan, 172., 152.,  92.,  53.,  13.,  66.,  26., 165.,  38.,
        36.,  47., 230.,  16.,  65., 332.,  58.,  14.,   9.,  17., 105.,
       210., 114.,  10.,  34.,   7.,  25.,  32., 133.,   8.,  12., 175.,
       174.,  23., 166.,  68., 128.,  91., 116.,  76.,  63., 106., 132.,
        64., 102.,  69., 103., 157.,  75., 118., 151., 104.,  56.,  33.,
        45.,   3.,  88.,  72.,  96.,  81.,  41.,  93.,  48.,  97.,  79.,
        85.,  42.,  30., 115.,  87.,  37.,  40., 108.,  84.,  90.,  67.,
        50., 150.,  46.,  59.,  43., 162., 171., 131.,  54., 159.,  60.,
        55.,  39., 147.,  51., 178., 122.,  98., 295.,  52., 113.,  71.,
       169., 187.,  95.,  70.,  57., 101.,  89., 130.,  62.,  78.,   2.,
        83., 194.,  49., 119.,   1., 136., 100.,  61., 124., 117., 168.,
       125.,  80., 120., 121., 167., 155., 144.,  8

In [41]:
pd.unique(financial_services["Global"])

array([False, True, nan], dtype=object)

In [42]:
financial_services.dtypes

name                          object
rating                       float64
reviews                       object
company_type                  object
Head_Quarters                 object
Company_Age                   object
No_of_Employee                object
rating_is_missing               bool
company_type_is_missing         bool
Head_Quarters_is_missing        bool
Company_Age_is_missing          bool
No_of_Employee_is_missing       bool
reviews_in_no                float64
number_of_headquarters       float64
company_age_in_years         float64
Global                        object
dtype: object

In [43]:
financial_services.isna().sum()

name                            0
rating                         20
reviews                         0
company_type                 5284
Head_Quarters                1300
Company_Age                  5027
No_of_Employee               3769
rating_is_missing               0
company_type_is_missing         0
Head_Quarters_is_missing        0
Company_Age_is_missing          0
No_of_Employee_is_missing       0
reviews_in_no                   0
number_of_headquarters       1300
company_age_in_years         5027
Global                       3769
dtype: int64

In [44]:
financial_services.head().T

0  \
name                                           ICICI Bank   
rating                                                4.0   
reviews                                   (33.6k Reviews)   
company_type                                       Public   
Head_Quarters              Mumbai,Maharashtra + 1020 more   
Company_Age                                  28 years old   
No_of_Employee                                    1 Lakh+   
rating_is_missing                                   False   
company_type_is_missing                             False   
Head_Quarters_is_missing                            False   
Company_Age_is_missing                              False   
No_of_Employee_is_missing                           False   
reviews_in_no                                     33600.0   
number_of_headquarters                             1021.0   
company_age_in_years                                 28.0   
Global                                              False   

                                                        1  \
name                                            HDFC Bank   
rating                                                4.0   
reviews                                   (37.9k Reviews)   
company_type                                       Public   
Head_Quarters              Mumbai,Maharashtra + 1168 more   
Company_Age                                  28 years old   
No_of_Employee                                    1 Lakh+   
rating_is_missing                                   False   
company_type_is_missing                             False   
Head_Quarters_is_missing                            False   
Company_Age_is_missing                              False   
No_of_Employee_is_missing                           False   
reviews_in_no                                     37900.0   
number_of_headquarters                             1169.0   
company_age_in_years                                 28.0   
Global                                              False   

                                                        2  \
name                                     HCL Technologies   
rating                                                3.9   
reviews                                   (17.4k Reviews)   
company_type                                       Public   
Head_Quarters              Noida,Uttar Pradesh + 138 more   
Company_Age                                  31 years old   
No_of_Employee                                    1 Lakh+   
rating_is_missing                                   False   
company_type_is_missing                             False   
Head_Quarters_is_missing                            False   
Company_Age_is_missing                              False   
No_of_Employee_is_missing                           False   
reviews_in_no                                     17400.0   
number_of_headquarters                              139.0   
company_age_in_years                                 31.0   
Global                                              False   

                                                        3  \
name                                            Axis Bank   
rating                                                3.9   
reviews                                   (18.3k Reviews)   
company_type                                       Public   
Head_Quarters              Mumbai,Maharashtra + 1041 more   
Company_Age                                  29 years old   
No_of_Employee                                    1 Lakh+   
rating_is_missing                                   False   
company_type_is_missing                             False   
Head_Quarters_is_missing                            False   
Company_Age_is_missing                              False   
No_of_Employee_is_missing                           False   
reviews_in_no                                     18300.0   
number_of_headquarters                             1042.0   
company_age_in_years       

# After seeing the result we can conclude that, we have successfully cleaned the data.

# Now we are going to fill the missing values in our dataframe

In [45]:
financial_services["Company_Age"]=financial_services["Company_Age"].ffill(axis=0)
financial_services["company_age_in_years"]=financial_services["company_age_in_years"].ffill(axis=0)
financial_services["number_of_headquarters"]=financial_services["number_of_headquarters"].ffill(axis=0)
financial_services["Head_Quarters"]=financial_services["Head_Quarters"].ffill(axis=0)
financial_services["No_of_Employee"]=financial_services["No_of_Employee"].ffill(axis=0)
financial_services["Global"]=financial_services["Global"].ffill(axis=0)
financial_services["company_type"].fillna("Unknown",inplace=True)

In [46]:
financial_services["company_type"]=financial_services["company_type"].astype("category")
financial_services["No_of_Employee"]=financial_services["No_of_Employee"].astype("category")

In [47]:
financial_services=financial_services.dropna()

In [48]:
financial_services.head().T

0  \
name                                           ICICI Bank   
rating                                                4.0   
reviews                                   (33.6k Reviews)   
company_type                                       Public   
Head_Quarters              Mumbai,Maharashtra + 1020 more   
Company_Age                                  28 years old   
No_of_Employee                                    1 Lakh+   
rating_is_missing                                   False   
company_type_is_missing                             False   
Head_Quarters_is_missing                            False   
Company_Age_is_missing                              False   
No_of_Employee_is_missing                           False   
reviews_in_no                                     33600.0   
number_of_headquarters                             1021.0   
company_age_in_years                                 28.0   
Global                                              False   

                                                        1  \
name                                            HDFC Bank   
rating                                                4.0   
reviews                                   (37.9k Reviews)   
company_type                                       Public   
Head_Quarters              Mumbai,Maharashtra + 1168 more   
Company_Age                                  28 years old   
No_of_Employee                                    1 Lakh+   
rating_is_missing                                   False   
company_type_is_missing                             False   
Head_Quarters_is_missing                            False   
Company_Age_is_missing                              False   
No_of_Employee_is_missing                           False   
reviews_in_no                                     37900.0   
number_of_headquarters                             1169.0   
company_age_in_years                                 28.0   
Global                                              False   

                                                        2  \
name                                     HCL Technologies   
rating                                                3.9   
reviews                                   (17.4k Reviews)   
company_type                                       Public   
Head_Quarters              Noida,Uttar Pradesh + 138 more   
Company_Age                                  31 years old   
No_of_Employee                                    1 Lakh+   
rating_is_missing                                   False   
company_type_is_missing                             False   
Head_Quarters_is_missing                            False   
Company_Age_is_missing                              False   
No_of_Employee_is_missing                           False   
reviews_in_no                                     17400.0   
number_of_headquarters                              139.0   
company_age_in_years                                 31.0   
Global                                              False   

                                                        3  \
name                                            Axis Bank   
rating                                                3.9   
reviews                                   (18.3k Reviews)   
company_type                                       Public   
Head_Quarters              Mumbai,Maharashtra + 1041 more   
Company_Age                                  29 years old   
No_of_Employee                                    1 Lakh+   
rating_is_missing                                   False   
company_type_is_missing                             False   
Head_Quarters_is_missing                            False   
Company_Age_is_missing                              False   
No_of_Employee_is_missing                           False   
reviews_in_no                                     18300.0   
number_of_headquarters                             1042.0   
company_age_in_years       

In [49]:
financial_services.shape

(8950, 16)

In [50]:
financial_services.dtypes

name                           object
rating                        float64
reviews                        object
company_type                 category
Head_Quarters                  object
Company_Age                    object
No_of_Employee               category
rating_is_missing                bool
company_type_is_missing          bool
Head_Quarters_is_missing         bool
Company_Age_is_missing           bool
No_of_Employee_is_missing        bool
reviews_in_no                 float64
number_of_headquarters        float64
company_age_in_years          float64
Global                           bool
dtype: object

In [51]:
financial_services.isna().sum()

name                         0
rating                       0
reviews                      0
company_type                 0
Head_Quarters                0
Company_Age                  0
No_of_Employee               0
rating_is_missing            0
company_type_is_missing      0
Head_Quarters_is_missing     0
Company_Age_is_missing       0
No_of_Employee_is_missing    0
reviews_in_no                0
number_of_headquarters       0
company_age_in_years         0
Global                       0
dtype: int64

# Now finaly cleaned the data to draw some insights from it.

# It times to save our data in our storage

In [52]:
financial_services.to_csv("financial_services_cleaned.csv")